<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="R&amp;D Team">
<meta name="dcterms.date" content="2026-03-01">

<title>AI Newsletter #01 – Kolmogorov-Arnold Networks! – CAIS Newsletter</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-7c64815504b6e2855bcc68556ce44afc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="dark">
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../logo.png" alt="" class="navbar-logo light-content">
    <img src="../logo.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">CAIS Newsletter</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background-and-introduction" id="toc-background-and-introduction" class="nav-link active" data-scroll-target="#background-and-introduction">Background and Introduction</a></li>
  <li><a href="#unpacking-the-theorem" id="toc-unpacking-the-theorem" class="nav-link" data-scroll-target="#unpacking-the-theorem">Unpacking the Theorem</a></li>
  <li><a href="#architectural-intuition" id="toc-architectural-intuition" class="nav-link" data-scroll-target="#architectural-intuition">Architectural Intuition</a></li>
  <li><a href="#why-kans-matter" id="toc-why-kans-matter" class="nav-link" data-scroll-target="#why-kans-matter">Why KANs Matter</a></li>
  <li><a href="#siren-kan" id="toc-siren-kan" class="nav-link" data-scroll-target="#siren-kan">SIREN-KAN</a></li>
  <li><a href="#pseudo--code-overview" id="toc-pseudo--code-overview" class="nav-link" data-scroll-target="#pseudo--code-overview">(Pseudo-) Code overview</a></li>
  <li><a href="#the-stress-test-high-frequency-radial-ripples" id="toc-the-stress-test-high-frequency-radial-ripples" class="nav-link" data-scroll-target="#the-stress-test-high-frequency-radial-ripples">The Stress Test: High-Frequency Radial Ripples</a></li>
  <li><a href="#experimental-setup" id="toc-experimental-setup" class="nav-link" data-scroll-target="#experimental-setup">Experimental Setup</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#final-comparison" id="toc-final-comparison" class="nav-link" data-scroll-target="#final-comparison">Final Comparison</a></li>
  <li><a href="#a-note-on-initialization" id="toc-a-note-on-initialization" class="nav-link" data-scroll-target="#a-note-on-initialization">A note on initialization</a></li>
  <li><a href="#conclusion-and-when-to-use-a-kan" id="toc-conclusion-and-when-to-use-a-kan" class="nav-link" data-scroll-target="#conclusion-and-when-to-use-a-kan">Conclusion and When to Use a KAN</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">AI Newsletter #01 – Kolmogorov-Arnold Networks!</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Newsletters</div>
    <div class="quarto-category">Machine Learning</div>
    <div class="quarto-category">Kolmogorov-Arnold Networks</div>
    <div class="quarto-category">Neural Networks</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>R&amp;D Team </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div style="height: 40px;">

</div>
<section id="background-and-introduction" class="level2">
<h2 class="anchored" data-anchor-id="background-and-introduction">Background and Introduction</h2>
<blockquote class="blockquote">
<p>Exploring the power of Kolmogorov-Arnold Networks for smarter, sharper function approximation.</p>
</blockquote>
<p>Welcome to our first newsletter! We’ll start with a bit of background on the math and architecture behind KANs, then go through a KAN implementation. The GitHub repo for everything is linked at the end of the article. Along the way, we’ll share some interesting empirical results and try to build an intuition for how it all works. Hope you enjoy it!</p>
<hr>
<p><strong>The MLP architecture and limitations</strong><br>
Standard multi-layer perceptrons (MLPs) place fixed activation functions (ReLU, SiLU, etc.) <em>inside the nodes</em>. Linear transformations (weights) live on the <em>edges</em>. This architecture forces the network to approximate any target function by stitching together many global hyperplanes. This is an approach that works but is extremely parameter-inefficient for smooth, high-frequency, or compositional functions (eg. <span class="math inline">\(f(g(x))\)</span>).</p>
<p><strong>The KAN architecture and applications</strong><br>
KANs generated significant excitement in the ML community around 2024, as researchers recognized their potential to drastically improve function representation with fewer parameters and more interpretable structure. The hype was fueled by early benchmarks showing remarkably efficient interpolation, sparking interest in both theoretical exploration and practical applications.</p>
<p>Kolmogorov-Arnold Networks (KANs) achieve this by mitigating key limitations of traditional neural architectures. They eliminate fixed node activations entirely: every edge becomes a learnable univariate function φ, and every node simply sums its incoming signals. The entire network is thus a composition of univariate functions and summations, precisely the structure promised by the famous Kolmogorov-Arnold representation theorem.</p>
</section>
<section id="unpacking-the-theorem" class="level2">
<h2 class="anchored" data-anchor-id="unpacking-the-theorem">Unpacking the Theorem</h2>
<p>The Kolmogorov-Arnold representation theorem (refined in the 1960s) states that any continuous multivariate function&nbsp;<span class="math inline">\(f: [0,1]^n \to \mathbb{R}\)</span>&nbsp;can be written as:</p>
<p><span class="math display">\[f(\mathbf{x}) = \sum_{q=1}^{2n+1} \Phi_q \left( \sum_{p=1}^n \phi_{q,p}(x_p) \right)\]</span></p>
<p>That’s a fantastic guarantee, but throwing raw equations at a problem doesn’t help us write code. To make this useful, we need to map the math directly to a network architecture.</p>
<ul>
<li><p>Inner edges <span class="math inline">\(\phi_{q,p}(x_p)\)</span>: Instead of mixing inputs right away like in an MLP, each input (<span class="math inline">\(x_p\)</span>) is first passed through its own separate 1D function, completely independent of the others.</p></li>
<li><p>Intermediate nodes <span class="math inline">\(\sum_{p=1}^n\)</span>: After that, the transformed inputs are just added together. No activation here, just a sum.</p></li>
<li><p>Outer edges <span class="math inline">\(\Phi_q\)</span>: So how do we capture interactions like <span class="math inline">\(x_1 \cdot x_2\)</span> if we only add things? That happens here. A final nonlinear 1D function is applied to the sum, which lets the model represent those interactions.</p></li>
<li><p>Hidden dimension <span class="math inline">\(2n+1\)</span>: This is the key guarantee. With <span class="math inline">\(n\)</span> inputs, you only need <span class="math inline">\(2n+1\)</span> of these nodes to represent any continuous function (e.g., 5 nodes for 2D input).</p></li>
</ul>
</section>
<section id="architectural-intuition" class="level2">
<h2 class="anchored" data-anchor-id="architectural-intuition">Architectural Intuition</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {
  "theme": "base",
  "themeVariables": {
    "background": "#222222",
    "primaryColor": "#2d2d2d",
    "primaryBorderColor": "#00bc8c",
    "primaryTextColor": "#ffffff",
    "secondaryColor": "#2d2d2d",
    "tertiaryColor": "#2d2d2d",
    "lineColor": "#00bc8c",
    "edgeLabelBackground": "#222222",
    "clusterBkg": "#2d2d2d",
    "clusterBorder": "#00bc8c",
    "titleColor": "#adb5bd",
    "fontFamily": "Source Sans Pro, Lato, sans-serif",
    "fontSize": "14px"
  },
  "flowchart": {"curve": "basis", "rankSpacing": 85, "nodeSpacing": 105}
}}%%
graph LR
    %% Define Nodes
    x1["x₁"]
    x2["x₂"]
    
    %% Connections from x1
    x1 --&gt;|"φ₁,₁(x₁)"| H1["Σ₁#160;"]
    x1 --&gt;|"φ₂,₁(x₁)"| H2["Σ₂#160;"]
    x1 --&gt;|"φ₃,₁(x₁)"| H3["Σ₃#160;"]
    
    %% Connections from x2
    x2 --&gt;|"φ₁,₂(x₂)"| H1
    x2 --&gt;|"φ₂,₂(x₂)"| H2
    x2 --&gt;|"φ₃,₂(x₂)"| H3
    
    %% Connections to Output
    H1 --&gt;|"Φ₁(Σ₁)#160;"| OUT["f(x) (Σ)"]
    H2 --&gt;|"Φ₂(Σ₂)#160;"| OUT
    H3 --&gt;|"Φ₃(Σ₃)#160;"| OUT
    
    %% Subgraphs
    subgraph IN["Inputs (n)"]
        x1
        x2
    end
    
    subgraph L1["Inner sums (2n+1)"]
        H1
        H2
        H3
    end
    
    subgraph OUT_G["Final output"]
        OUT
    end
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Note: This graph shows a Kolmogorov–Arnold Network (KAN) for <span class="math inline">\((n=2)\)</span>, using three inner nodes for clarity instead of the <span class="math inline">\(2n+1\)</span> required by the theorem.</p>
<blockquote class="blockquote">
<p><span class="math inline">\(x_i\)</span> (Inputs) : The initial input features fed into the network.</p>
</blockquote>
<blockquote class="blockquote">
<p><span class="math inline">\(\phi\)</span> (Edges) : The defining feature of a KAN. Instead of static weights (<span class="math inline">\(w\)</span>), edges contain learnable univariate functions (e.g., B-splines).</p>
</blockquote>
<blockquote class="blockquote">
<p><span class="math inline">\(\sum \phi(x)\)</span> (Nodes) : Nodes simply sum incoming signals. That means no activation, just aggregating the signals!</p>
</blockquote>
<blockquote class="blockquote">
<p><span class="math inline">\(f(x)\)</span> (Output) : The final multivariate function built from compositions of 1D functions.</p>
</blockquote>
<p><br></p>
</section>
<section id="why-kans-matter" class="level2">
<h2 class="anchored" data-anchor-id="why-kans-matter">Why KANs Matter</h2>
<p>The Kolmogorov-Arnold theorem has been around since the 1950s. What changed is that we can now learn those univariate functions end-to-end with gradient descent, effectively turning a theoretical existence proof into a working architecture.</p>
<p><strong>Where KANs shine</strong></p>
<ul>
<li><p><strong>Scientific discovery and symbolic regression.</strong> Each edge is a univariate function, so you can prune the network and literally read off the learned expression, i.e.&nbsp;“this edge learned <span class="math inline">\(x²\)</span>, that one learned <span class="math inline">\(sin(3πx)\)</span>.” For physics, chemistry, and biology, that could be the foundation for new discoveries!</p></li>
<li><p><strong>Physics and PDE solvers.</strong> KANs respect compositional structure naturally, so they extrapolate far better than MLPs when solving differential equations outside the training domain.</p></li>
<li><p><strong>High-frequency and periodic phenomena.</strong> As the radial sine ripple demo will show later, KANs (especially SIREN-KAN variants) can capture rapid oscillations with far fewer parameters.</p></li>
<li><p><strong>Low-to-medium dimensional problems.</strong> Financial time series, engineering simulations, control systems. Tasks with roughly 2–20 input dimensions, where interpretability and reliable extrapolation are important.</p></li>
</ul>
<p><br> <strong>They have been hyped, but is it justified?</strong></p>
<p>MLPs approximate complex surfaces by overlapping vast numbers of flat hyperplanes. KANs follow the exact decomposition that the theorem guarantees exists, which gives them real structural advantages: often 10–100× fewer parameters on smooth functions, better out-of-distribution behavior, and interpretable edges you can inspect or symbolically regress.</p>
<p>MLPs are excellent for messy, high-dimensional data like images and text. KANs on the other hand are what you should apply when you suspect there’s an underlying mathematical law to be found.</p>
</section>
<section id="siren-kan" class="level2">
<h2 class="anchored" data-anchor-id="siren-kan">SIREN-KAN</h2>
<p>The <strong><a href="https://arxiv.org/abs/2404.19756">original KAN paper (Liu et al., 2024)</a></strong> parameterised the univariate edge functions <span class="math inline">\(\phi\)</span> with B-splines. This choice gives excellent localisation and interpretability, but B-splines struggle with high-frequency oscillations (which is what we are going to be testing here!) because they are inherently low-pass (smooth polynomial pieces).</p>
<p>When people replace B-splines with tiny MLPs (a common simplification in early re-implementations), the network inherits the spectral bias of standard MLPs and fails to capture rapid oscillations.</p>
<p><br> <strong>The SIREN-KAN solution</strong></p>
<p>In this implementation we will replace the activation inside each edge with a SIREN-style periodic basis: <span class="math inline">\(sin(\omega_0 x + b)\)</span>. By scaling the first-layer frequencies with <span class="math inline">\(\omega_0\)</span> and using careful initialisation, each univariate edge gains infinite periodic capacity. The result is a network that can learn the exact algebraic structure of high-frequency targets (e.g.&nbsp;sin(polynomial)) with dramatically fewer parameters.</p>
</section>
<section id="pseudo--code-overview" class="level2">
<h2 class="anchored" data-anchor-id="pseudo--code-overview">(Pseudo-) Code overview</h2>
<p>This is the rough KAN architecture:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># full repo is separate (see bottom)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> layer <span class="kw">in</span> KAN_layers:</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Inner univariate functions (one per edge)</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> every input_dim → hidden_dim edge:</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>        φ <span class="op">=</span> sin(ω₀·x <span class="op">+</span> b)               <span class="co"># SIREN-style</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>        edge_out <span class="op">=</span> linear(φ)            <span class="co"># small projection</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    h <span class="op">=</span> <span class="bu">sum</span>(edge_out over input_dim)    <span class="co"># node sums</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Outer univariate functions</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> every hidden_dim → out_dim edge:</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>        Φ <span class="op">=</span> sin(ω₀·h <span class="op">+</span> b)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>        edge_out <span class="op">=</span> linear(Φ)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> <span class="bu">sum</span>(edge_out over hidden_dim)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="the-stress-test-high-frequency-radial-ripples" class="level2">
<h2 class="anchored" data-anchor-id="the-stress-test-high-frequency-radial-ripples">The Stress Test: High-Frequency Radial Ripples</h2>
<p>Target function (chosen to be analytically simple yet extremely difficult for spectral-biased networks): <span class="math display">\[
f(x_1, x_2) = \sin\bigl(3\pi(x_1^2 + x_2^2)\bigr)
\]</span></p>
<p>This is a radially symmetric sine wave whose frequency increases quadratically with distance from the origin, basically a perfect stress test for extrapolation.</p>
</section>
<section id="experimental-setup" class="level2">
<h2 class="anchored" data-anchor-id="experimental-setup">Experimental Setup</h2>
<p>To rigorously evaluate whether these architectures actually learn the underlying mathematical rules, we analyzed performance within the training domain and also conducted a strict out-of-distribution (OOD) extrapolation test.</p>
<ul>
<li><p><strong>The Competitors:</strong>&nbsp;A standard Multi-Layer Perceptron (two 64-neuron hidden layers, ~4,400 parameters) relying on global hyperplanes, matched against our custom SIREN-KAN (hidden dimension of 5, ~375 parameters) equipped with localized, frequency-scaled sine activations.</p></li>
<li><p><strong>The Training Domain (Interpolation):</strong>&nbsp;Both models were trained exclusively on uniformly sampled data within the boundary&nbsp;<span class="math inline">\(x_1, x_2 \in [-1.2, 1.2]\)</span>. This provides a solid, bounded view of the central concentric ripples.</p></li>
<li><p><strong>The Testing Domain (Extrapolation):</strong>&nbsp;We then evaluated their predictive power on an expanded grid spanning&nbsp;<span class="math inline">\([-1.4, 1.4]\)</span>.</p></li>
</ul>
<p>Why it matters: Neural networks are usually great at interpolating, but extrapolating? Not so much. If a network just memorizes the space by patching together overlapping linear segments (like a standard MLP), its predictions will fall apart as soon as you move past the <span class="math inline">\(1.2\)</span> boundary.</p>
<p>On the other hand, if a network’s inductive bias really captures the underlying periodic pattern, the exact boundary shouldn’t matter. Our hypothesis was that the KAN would handle this out-of-domain prediction much better.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<div id="fig-surfaces" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-surfaces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/1-kan/MLP_vs_KAN_2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-surfaces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: 3D Surface Comparison: The MLP struggles with high-frequency ripples while the KAN maps them very well.
</figcaption>
</figure>
</div>
<p>The MLP shows a clear spectral bias: it handles the low-frequency, broad patterns near the origin pretty well, but completely misses the high-frequency details at the edges. The KAN, on the other hand, is much more expressive for this kind of problem, capturing both the coarse structure and the fine oscillations across the whole space.</p>
<div id="fig-surfaces" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-surfaces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/1-kan/MLP_vs_KAN_1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-surfaces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Training Dynamics and Prediction Fidelity.
</figcaption>
</figure>
</div>
<p><strong>Training Dynamics (Left):</strong></p>
<p>You can pretty clearly see the MLP struggling during training. It hits a plateau early and then keeps spiking all over the place, which is a classic sign that the optimizer is fighting itself trying to fit high-frequency signals with a rigid structure. The KAN, on the other hand, is much smoother. Around epoch ~450 it actually breaks through that plateau and keeps improving, ending up at a much lower MSE.</p>
<p><strong>Prediction Fidelity (Right):</strong></p>
<p>The scatter plot makes it even more obvious. The KAN predictions sit right around the dashed “perfect prediction” line across the whole range. The MLP is way more scattered. You can even see these horizontal bands (especially around y ≈ 0.25), which indicates that it has basically given up and is predicting constant values over big chunks of the input space. It’s not clearly capturing the structure of the data as well as the KAN.</p>
</section>
<section id="final-comparison" class="level2">
<h2 class="anchored" data-anchor-id="final-comparison">Final Comparison</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 36%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Architecture</strong></th>
<th><strong>Parameters</strong></th>
<th><strong>In-Distribution MSE <span class="math inline">\([-1.2, 1.2]\)</span></strong></th>
<th><strong>OOD MSE (<span class="math inline">\(&gt; \lvert 1.2 \rvert\)</span>)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>MLP (64x64)</strong></td>
<td>4,417</td>
<td>0.1063</td>
<td>1.8749</td>
</tr>
<tr class="even">
<td><strong>SIREN-KAN</strong></td>
<td>375</td>
<td>0.0014</td>
<td>0.2929</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Interpolation:</strong></p>
<p>Within the training domain, the Kolmogorov-Arnold Network performs exceptionally well. It achieved a near-perfect MSE of 0.0014 compared to the MLP’s 0.1063, a 98.7% reduction in error. It achieves this while using roughly 12x fewer parameters, proving that its periodic 1D edges natively capture high-frequency ripples far better than the MLP’s overlapping global hyperplanes.</p>
<p><strong>Extrapolation:</strong></p>
<p>The out-of-distribution test reveals the true power of the architecture’s inductive bias. The MLP fails catastrophically (MSE 1.87). Because it merely memorized the spatial grid, it runs out of hyperplanes past the 1.2 boundary and predicts chaotic noise.</p>
<p>The SIREN-KAN, however, successfully holds its structural integrity outside the training bounds (MSE 0.29). By deeply converging on the correct phase alignments of its internal sine waves, it managed to parameterize the periodic-quadratic structure well enough to accurately project the ripples into unseen space. <br></p>
</section>
<section id="a-note-on-initialization" class="level2">
<h2 class="anchored" data-anchor-id="a-note-on-initialization">A note on initialization</h2>
<p>Normal networks “play it safe” and start with tiny weights to keep training stable. But in this case, a sine wave is basically flat around zero. Feed in tiny weights, and every sine in the network acts like a straight line. Your flexible KAN “flatlines” and loses all ability to bend around the data.</p>
<p><strong>The Fix:</strong></p>
<p>Borrowing a trick from SIRENs, we amplify the first layer’s weights, say 10×. This pushes signals out of the flat zone and forces the network to hit sine peaks and valleys from Epoch 0.</p>
<p><strong>The Trade-off:</strong></p>
<p>A hypersensitive, oscillating landscape means learning rates must be precise, if they are too high, the optimizer will most likely bounce away. SIREN-KANs are extremely powerful, but far less forgiving than standard MLPs in this regard. So we had to initialize them multiple times before achieving a good representation!</p>
</section>
<section id="conclusion-and-when-to-use-a-kan" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-and-when-to-use-a-kan">Conclusion and When to Use a KAN</h2>
<p>Kolmogorov–Arnold Networks actually feel like a different way of thinking about neural networks. Instead of relying on rigid hyperplanes, they learn flexible one-dimensional functions, which lines up nicely with the Kolmogorov–Arnold theorem. In practice, that means better accuracy, far fewer parameters, and models that are easier to interpret.</p>
<p>The radial ripple experiment makes this pretty clear: about 12× fewer parameters, almost perfect interpolation, and much more stable behavior outside the training range, where a standard MLP tends to fall apart. That’s the core reason KANs (and SIREN-style variants) are getting so much attention.</p>
<hr>
<p><strong>Final recommendation - Use a KAN when:</strong></p>
<ul>
<li><p>You need parameter-efficient approximation of smooth, highly compositional, or periodic physical/symbolic equations.</p></li>
<li><p>Interpretability matters — <em>pruning</em> the univariate functions yields human-readable symbolic expressions!</p></li>
<li><p>You are operating in low-to-medium input dimensionality <span class="math inline">\((n \lesssim 20)\)</span>.</p></li>
</ul>
<p><strong>Do NOT use a KAN when</strong></p>
<ul>
<li>Input dimensionality is extreme (raw images, text tokens, etc.). The (2n+1) inner-sum expansion becomes a computational bottleneck and standard Transformers or MLPs still dominate here.</li>
</ul>
<hr>
<p>Easiest way to see how it works is to clone the repo!</p>
<blockquote class="blockquote">
<p>Full reproducible notebook → <a href="https://github.com/manswestman/KAN-basics">manswestman/KAN-basics</a></p>
</blockquote>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/manswestman\.github\.io\/ai-news\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>